# Libraries

In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [2]:
import os

# Data

In [3]:
dataset = pd.read_csv('featureset.csv')

In [4]:
testset = pd.read_csv('testset.csv')

In [5]:
dataset.head()

URL  Label  \
0                                    https://nih.gov      0   
1                        http://www.perfumemart.com/      0   
2  http://chronopost-service-enligne.net/56123s/r...      1   
3  http://wvw.micloudappel.security-updates-myacc...      1   
4  http://colach8x.beget.tech/likon/mqnger/drwx/P...      1   

   Domain Registration Length  Search Traffic  Bounce Rate  \
0                          -1            72.9         57.3   
1                          -1            -1.0         50.0   
2                          -1            -1.0         -1.0   
3                          -1            -1.0         -1.0   
4                           4             5.1         45.7   

   Total Sites Linking in    Alexa Rank  Daily Views per Visitor  \
0                  134142  8.849558e-03                     3.17   
1                      -1  1.925435e-07                    -1.00   
2                      -1 -1.000000e+00                    -1.00   
3                      -1 -1.000000e+00                    -1.00   
4                    7352  5.198586e-05                     5.76   

   Daily Time on Site  Length  Is IP  Count @  Count Double Slash  \
0                 237      15      0        0                   1   
1                  -1      27      0        0                   1   
2                  -1     116      0        0                   1   
3                  -1      75      0        0                   1   
4                 697     139      0        0                   1   

   Count Hyphen  Count Dots  Count Delimeters  Count Subdirectory  \
0             0           1                 0                   2   
1             0           2                 0                   3   
2             2           1                 0                   8   
3             2           3                 0                   5   
4             0           3                 3                  11   

   Count Queries  
0              1  
1              1  
2              1  
3              1  
4              1

In [6]:
testset.head()

URL  Domain Registration Length  \
0           https://www.office.com                          20   
1            https://www.google.de                          -1   
2       https://www.tribunnews.com                           9   
3  https://www.microsoftonline.com                          18   
4             https://www.imdb.com                          27   

   Search Traffic  Bounce Rate  Total Sites Linking in  Alexa Rank  \
0            22.6         58.6                    7285    0.019608   
1             5.3         37.3                   52993    0.016129   
2            75.0         49.7                   39300    0.027027   
3             1.2         47.2                    1106    0.030303   
4            57.9         41.5                  214337    0.020000   

   Daily Views per Visitor  Daily Time on Site  Length  Is IP  Count @  \
0                     2.52                 201      22      0        0   
1                     5.27                 240      21      0        0   
2                     2.65                 261      26      0        0   
3                     1.91                  73      31      0        0   
4                     4.07                 209      20      0        0   

   Count Double Slash  Count Hyphen  Count Dots  Count Delimeters  \
0                   1             0           2                 0   
1                   1             0           2                 0   
2                   1             0           2                 0   
3                   1             0           2                 0   
4                   1             0           2                 0   

   Count Subdirectory   Count Queries   Label  
0                    2               1      0  
1                    2               1      0  
2                    2               1      0  
3                    2               1      0  
4                    2               1      0

In [7]:
print(dataset.shape, testset.shape)

(8000, 18) (99, 18)


In [8]:
X = dataset.drop(['URL', 'Label'], axis=1)
y = dataset['Label']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_eval, y_train, y_eval = train_test_split(X, y, test_size=0.2887, random_state=101)

In [11]:
X_test = testset.drop(['URL','Label'], axis=1)
y_test = testset['Label']

# Machine Learning

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score

## Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
model = LogisticRegression()
accuracies = cross_val_score(estimator=model, X=X, y=y, cv=10)
print("{} +- ({})".format(accuracies.mean(), accuracies.std()))

LR = LogisticRegression()
LR.fit(X, y)
y_pred = LR.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.885 +- (0.010796411440844587)
[[45  4]
 [ 1 49]]
              precision    recall  f1-score   support

           0       0.98      0.92      0.95        49
           1       0.92      0.98      0.95        50

   micro avg       0.95      0.95      0.95        99
   macro avg       0.95      0.95      0.95        99
weighted avg       0.95      0.95      0.95        99



## Random Forest Classifier

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
model = RandomForestClassifier()
accuracies = cross_val_score(estimator=model, X=X, y=y, cv=10)
print("{} +- ({})".format(accuracies.mean(), accuracies.std()))

RFC = RandomForestClassifier()
RFC.fit(X, y)
y_pred = RFC.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.955875 +- (0.005674779731408083)
[[48  1]
 [ 1 49]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        49
           1       0.98      0.98      0.98        50

   micro avg       0.98      0.98      0.98        99
   macro avg       0.98      0.98      0.98        99
weighted avg       0.98      0.98      0.98        99



## SVM

In [17]:
from sklearn.svm import SVC

In [18]:
model = SVC()
accuracies = cross_val_score(estimator=model, X=X, y=y, cv=10)
print("{} +- ({})".format(accuracies.mean(), accuracies.std()))

SVC_ = SVC()
SVC_.fit(X, y)
y_pred = SVC_.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9109999999999999 +- (0.005857687256929983)
[[48  1]
 [25 25]]
              precision    recall  f1-score   support

           0       0.66      0.98      0.79        49
           1       0.96      0.50      0.66        50

   micro avg       0.74      0.74      0.74        99
   macro avg       0.81      0.74      0.72        99
weighted avg       0.81      0.74      0.72        99



# Model Pickeling

In [19]:
import pickle

In [23]:
DIR = 'E:/Models/URL-Classfier'

In [21]:
pickle.dump(LR, open(f'{DIR}/LR.pickle', 'wb'))

In [22]:
pickle.dump(RFC, open(f'{DIR}/RFC.pickle', 'wb'))

In [24]:
pickle.dump(SVC_, open(f'{DIR}/SVC.pickle', 'wb'))

# Deeplearning

**Architecture**

16->80->400->20->1

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()
X_scaled_train = scaler.fit_transform(X)
X_scaled_test = scaler.transform(X_test)
pickle.dump(scaler, open(f'{DIR}/Scaler.pickle', 'wb'))

In [27]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import EarlyStopping, ModelCheckpoint

Using TensorFlow backend.


In [28]:
es = EarlyStopping(monitor='loss', mode='min', verbose=1)
filepath = f'{DIR}/model.h5'
ckpt = ModelCheckpoint(filepath, monitor='loss', verbose=1, save_best_only=True, mode='min')

In [29]:
def build_network():
    model = Sequential()
    model.add(Dense(80,input_dim=16, activation='relu'))
    model.add(Dropout(0.2))
    model.add(Dense(400, activation='relu'))
    model.add(Dropout(0.2))
    model.add(Dense(20, activation='relu'))
    model.add(Dropout(0.2))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.summary()
    return model

In [30]:
model = build_network()

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 80)                1360      
_________________________________________________________________
dropout_1 (Dropout)          (None, 80)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 400)               32400     
_________________________________________________________________
dropout_2 (Dropout)          (None, 400)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 20)                8020      
_________________________________________________________________
dropout_3 (Dropout)  

In [31]:
model.fit(X_scaled_train, y, validation_split=0.2887, epochs=25, callbacks=[es, ckpt])

Instructions for updating:
Use tf.cast instead.
Train on 5690 samples, validate on 2310 samples
Epoch 1/25
5690/5690 [==============================] - 4s 724us/step - loss: 0.2591 - acc: 0.8953 - val_loss: 0.1886 - val_acc: 0.9130

Epoch 00001: loss improved from inf to 0.25907, saving model to E:/Models/URL-Classfier/model.h5
Epoch 2/25
5690/5690 [==============================] - 1s 126us/step - loss: 0.2010 - acc: 0.9181 - val_loss: 0.1716 - val_acc: 0.9346

Epoch 00002: loss improved from 0.25907 to 0.20103, saving model to E:/Models/URL-Classfier/model.h5
Epoch 3/25
5690/5690 [==============================] - 1s 127us/step - loss: 0.1902 - acc: 0.9258 - val_loss: 0.1551 - val_acc: 0.9381

Epoch 00003: loss improved from 0.20103 to 0.19017, saving model to E:/Models/URL-Classfier/model.h5
Epoch 4/25
5690/5690 [==============================] - 1s 122us/step - loss: 0.1742 - acc: 0.9323 - val_loss: 0.1623 - val_acc: 0.9424

Epoch 00004: loss improved from 0.19017 to 0.17425, savin

In [32]:
y_pred = model.predict_classes(X_scaled_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[48  1]
 [ 1 49]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        49
           1       0.98      0.98      0.98        50

   micro avg       0.98      0.98      0.98        99
   macro avg       0.98      0.98      0.98        99
weighted avg       0.98      0.98      0.98        99

